[tools]
pulumi = "latest"

[tasks.preview-deployment]
description = "Perform a Pulumi dry-run (preview)"
run = """
pulumi login
pulumi preview --stack local
"""
dir = "iac"

[tasks.project-setup]
description = "Initialize local Pulumi state and stack"
run = """
pulumi install
pulumi login
pulumi stack select local
"""
dir = "iac"

[tasks.deploy]
description = "Apply Pulumi changes using local stack"
run = """
pulumi login
pulumi up --stack local
"""
dir = "iac"
